# constant defined in temporal https://github.com/temporalio/temporal/blob/master/common/dynamicconfig/constants.go

#frontend.enableClientVersionCheck:
#- value: true
#  constraints: {}
#history.persistenceMaxQPS:
#- value: 3000
#  constraints: {}
#frontend.persistenceMaxQPS:
#- value: 3000
#  constraints: {}
#frontend.throttledLogRPS:
#- value: 20
#  constraints: {}
#history.defaultActivityRetryPolicy:
#- value:
#    InitialIntervalInSeconds: 1
#    MaximumIntervalCoefficient: 100.0
#    BackoffCoefficient: 2.0
#    MaximumAttempts: 0
#history.defaultWorkflowRetryPolicy:
#- value:
#    InitialIntervalInSeconds: 1
#    MaximumIntervalCoefficient: 100.0
#    BackoffCoefficient: 2.0
#    MaximumAttempts: 0
#system.secondaryVisibilityWritingMode:
#  - value: "off"
#    constraints: {}
#system.enableReadFromSecondaryVisibility:
#  - value: false
#    constraints: {}
#system.enableParentClosePolicyWorker:
#  - value: true
system.enableEagerWorkflowStart:
  - value: true
limit.maxIDLength:
  - value: 255
    constraints: {}
frontend.workerVersioningDataAPIs:
  - value: true
frontend.workerVersioningWorkflowAPIs:
  - value: true
frontend.enableUpdateWorkflowExecution:
  - value: true
frontend.enableUpdateWorkflowExecutionAsyncAccepted:
  - value: true
limit.historyCount.error:
#history.historyCountLimitError:
  - value: 4
    constraints: {}
